---
- hosts: '{{ target }}'
  sudo: yes
  
  tasks:
  - name: install common packages for all servers
    yum: 
      state=latest
      name={{item}}
    with_items: 
    - bind-utils
    - git
    - hping3
    - htop
    - jq
    - lsof
    - mtr
    - ncdu
    - net-tools
    - nmap
    - nmap-ncat
    - pwgen
    - rsync
    - screen
    - socat
    - strace
    - sudo
    - tar
    - tcpdump
    - telnet
    - tmux
    - tree
    - unzip
    - vim-enhanced
    - wget
    - whois
    - zsh 
